name: Terraform Deploy to LocalStack
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"  # Versión estable más reciente

      - name: Install AWS CLI (for LocalStack)
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI for LocalStack
        run: |
          aws configure --profile localstack <<EOF
          test
          test
          us-east-1
          json
          EOF

      - name: Start LocalStack in Docker
        run: |
          docker run -d --name localstack \
            -p 4566:4566 \
            -e SERVICES=s3,ec2 \
            localstack/localstack

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
