name: Terraform Deploy to LocalStack
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Install AWS CLI (correct method)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Configure AWS CLI for LocalStack
        run: |
          aws configure --profile localstack <<EOF
          test
          test
          us-east-1
          json
          EOF

      - name: Start LocalStack in Docker
        run: |
          docker run -d --name localstack \
            -p 4566:4566 \
            -e SERVICES=s3,ec2 \
            localstack/localstack

      - name: Wait for LocalStack to be ready
        run: sleep 15  # Da a LocalStack tiempo para iniciarse

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
